import type { Metadata } from "next";
import { Newsreader, Noto_Sans } from 'next/font/google';
import "./globals.css";
import AuthProvider from './providers/AuthProviders';
import { Toaster } from 'sonner';

const newsreader = Newsreader({
  weight: ['400', '500', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

const notoSans = Noto_Sans({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${newsreader.className} ${notoSans.className}`}>
        <AuthProvider>
          <Toaster richColors position="top-right" />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
